### ISSUE TITLE
非常好的示例库，我想问下主页中的那个红色的嘴唇怎么去掉？

### ISSUE THREAD

**Issue by PandaK404** [SongshGeo/Obsidian-PaperBell#1]
![image](https://github.com/SongshGeo/Obsidian-PaperBell/assets/83934795/9048e237-fa0d-47ae-800e-b7038809e1ad)

项目追踪里的这个红色嘴唇，我找了一圈，没发现在哪删除

**Comment by SongshGeo** [comment]
非常抱歉，格式有关的可能要到 [rainbell 仓库](https://github.com/Rainbell129/Obsidian-Homepage)去问。我在文档里也有声明过，我的示例库仅展示工作流，不负责美化。
