### ISSUE TITLE
3.0版库中的中文文件夹和中文文件下载后是乱码

### ISSUE THREAD

**Issue by Aren-py** [SongshGeo/Obsidian-PaperBell#4]
3.0版的库下载后，库中的中文文件夹和文件都是乱码。
![image](https://github.com/user-attachments/assets/cc5eda64-5774-45d3-98bd-3313cbfaa6b5)

**Comment by SongshGeo** [comment]
应该是我用 Mac 原生压缩软件打包默认 utf-8 编码，在 Win 上解压缩 gbk 解码导致的问题。
我会在下个版本更新时使用更具兼容性的压缩工具，但最近比较忙，下个版本可能需要两周了。你可以尝试搜一下该问题，看看有没有什么解压的方案能够兼容。 ;)
