### ISSUE TITLE
非常好的示例库，感谢作者，不过遇到了一个小问题

### ISSUE THREAD

**Issue by Langzhousimawin** [SongshGeo/Obsidian-PaperBell#8]
如图，横幅无法显示...
![image](https://github.com/user-attachments/assets/1cea7bd2-b85b-42ef-b3df-895153b76170)

**Comment by SongshGeo** [comment]
能不能打开源代码模式，看看你的 properties 怎么写的？
以及有没有删除或移动过 `40 - Obsidian/img/` 路径下的文件？

**Comment by Langzhousimawin** [comment]
目前版本：V2.1.0
（ps.我刚刚看到3.0版本<2024.8.21>有img文件夹，而最新版2.1.0<2024.12.1>版本没有，我猜是这个原因了）
移植img文件夹后已经正常显示，再次感谢作者抽空解答疑惑❤️
<img width="541" alt="image" src="https://github.com/user-attachments/assets/1d8128f7-c5da-4f2c-94f0-2a47836daa72" />
![image](https://github.com/user-attachments/assets/d6f9f225-852f-4473-b8fa-ce350d864d13)

**Comment by SongshGeo** [comment]
谢谢你指出这个问题！
我刚刚已经排查到了错误，因为在最新的 GitHub release 中我使用了自动发布，而非之前手动打包。
自动发布由于`.gitignore`的设置，自动忽略上传了 `img` 文件夹，我正在修改以前的 releases 版本，以避免给以后的用户造成困扰。

**Comment by SongshGeo** [comment]
已经在最新的 PR #10  中进行了修复，其他用户只要下载最新 release 版本即可，问题关闭。
